### ISSUE TITLE
Great package! But can we choose to disable the messages?

### ISSUE THREAD

**Issue by nagman** [nambo/gulp-js-import#1]
I really love this package. It's ultra simple and does exactly what I wanted to do.

I was first going in trouble with browserify, which does complex things for simple purposes.

And with this package, I can now keep my global variables and split all my js in as many files I want.

Now I just want to disable the two console.logs, because I want to keep my console clear.

Is there an option for that?

**Comment by nambo** [comment]
hi, sorry for long time waiting! 
did you mean console like this
```
import filename --> path
```
or 
```
ImportJS finished.
```
i will support next version, thanks for suggestion.

**Comment by nambo** [comment]
i have add **hideConsole** config, you can use like this
```
var gulp = require('gulp');
var jsImport = require('gulp-js-import');

gulp.task('import', function() {
  return gulp.src('index.js')
        .pipe(jsImport({hideConsole: true}))
        .pipe(gulp.dest('dist'));
});
```

**Comment by nagman** [comment]
Cool, thanks!
